name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_with_unittests:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: submodule
      run: git submodule init; git submodule update
    - name: unittests
      run: make cpptest; make converttest
      
  verify_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: jellyfish
      run: sudo apt install jellyfish
    - name: verify
      run: make verify

